# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=4096)),
                ('information', models.TextField(max_length=65536)),
                ('infotext', models.TextField(max_length=65536)),
            ],
        ),
    ]
